scss_files: "**/*.scss"

linters:
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false

  BorderZero:
    enabled: false

  ColorKeyword:
    enabled: true
    severity: warning

  Comment:
    enabled: true

  DebugStatement:
    enabled: true

  DeclarationOrder:
    enabled: true

  DuplicateProperty:
    enabled: true

  ElsePlacement:
    enabled: true
    style: same_line

  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true

  EmptyRule:
    enabled: true

  FinalNewline:
    enabled: true
    present: true

  HexLength:
    enabled: true
    style: long

  HexNotation:
    enabled: true
    style: lowercase

  HexValidation:
    enabled: true

  IdWithExtraneousSelector:
    enabled: true

  ImportPath:
    enabled: true
    leading_underscore: false
    filename_extension: false

  Indentation:
    enabled: true
    character: space
    width: 2

  LeadingZero:
    enabled: true
    style: include_zero

  MergeableSelector:
    enabled: true
    force_nesting: true

  NameFormat:
    enabled: true
    convention: hyphenated_lowercase

  NestingDepth:
    enabled: true
    max_depth: 4
    severity: warning

  PlaceholderInExtend:
    enabled: false

  PropertySortOrder:
    enabled: true
    ignore_unspecified: false
    severity: warning
    # Order based on http://rhodesmill.org/brandon/2011/concentric-css/
    order:
      - display
      - position
      - box-sizing
      - top
      - right
      - bottom
      - left
      -
      - flex
      - flex-wrap
      - align-items
      - justify-content
      - align-self
      - flex-basis
      - flex-shrink
      - flex-direction
      -
      - columns
      - column-gap
      - column-fill
      - column-rule
      - column-span
      - column-count
      - column-width
      -
      - float
      - clear
      -
      - visibility
      - opacity
      - z-index
      -
      - margin
      - margin-top
      - margin-right
      - margin-bottom
      - margin-left
      -
      - outline
      -
      - border
      - border-top
      - border-right
      - border-bottom
      - border-left
      - border-width
      - border-top-width
      - border-right-width
      - border-bottom-width
      - border-left-width
      -
      - border-style
      - border-top-style
      - border-right-style
      - border-bottom-style
      - border-left-style
      -
      - border-radius
      - border-top-left-radius
      - border-top-right-radius
      - border-bottom-left-radius
      - border-bottom-right-radius
      -
      - border-color
      - border-top-color
      - border-right-color
      - border-bottom-color
      - border-left-color
      -
      - box-shadow
      -
      - background
      - background-color
      - background-image
      - background-repeat
      - background-position
      - background-size
      - cursor
      -
      - padding
      - padding-top
      - padding-right
      - padding-bottom
      - padding-left
      -
      - width
      - min-width
      - max-width
      -
      - height
      - min-height
      - max-height
      -
      - overflow
      -
      - list-style
      - caption-side
      -
      - table-layout
      - border-collapse
      - border-spacing
      - empty-cells
      -
      - vertical-align
      -
      - text-align
      - text-indent
      - text-transform
      - text-decoration
      - text-rendering
      - text-shadow
      - text-overflow
      -
      - line-height
      - word-spacing
      - letter-spacing
      - white-space
      - color
      -
      - font
      - font-family
      - font-size
      - font-weight
      - font-smoothing
      - font-style
      -
      - transform
      - transform-origin
      - transition
      - transition-property
      - transition-duration
      - transition-timing-function
      - transition-delay
      -
      - animation
      - animation-name
      - animation-duration
      - animation-delay
      - animation-fill-mode
      - animation-timing-function
      - animation-iteration-count
      -
      - content
      - quotes

  PropertySpelling:
    enabled: true
    extra_properties: []

  QualifyingElement:
    enabled: true
    allow_with_attribute: false
    allow_with_class: false
    allow_with_id: false
    severity: warning

  SelectorDepth:
    enabled: true
    max_depth: 4
    severity: warning

  SelectorFormat:
    enabled: true
    convention: hyphenated_lowercase

  Shorthand:
    enabled: true
    severity: warning

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: true

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: true

  SpaceAfterPropertyColon:
    enabled: true
    style: one_space

  SpaceAfterPropertyName:
    enabled: true

  SpaceBeforeBrace:
    enabled: true
    style: space
    allow_single_line_padding: false

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  StringQuotes:
    enabled: true
    style: double_quotes

  TrailingSemicolon:
    enabled: true

  TrailingZero:
    enabled: false

  UnnecessaryMantissa:
    enabled: true

  UnnecessaryParentReference:
    enabled: true

  UrlFormat:
    enabled: true

  UrlQuotes:
    enabled: true

  VendorPrefixes:
    enabled: true
    identifier_list: bourbon
    include: []
    exclude: []

  ZeroUnit:
    enabled: true
    severity: warning

  Compass::*:
    enabled: false
